import type { Farmer, Plantation } from '../types/farmer';

export const mockFarmers: Farmer[] = [
  {
    id: '1',
    name: 'John Smith',
    age: 45,
    photo: '',
    address: 'North Village, Plot 12',
    phone: '+62 812-3456-7890',
    experience: 20,
    landSize: 5.5,
    tobaccoVariety: 'Virginia',
    certifications: ['Organic Certified', 'GAP Certified'],
  },
  {
    id: '2',
    name: 'Maria Garcia',
    age: 38,
    photo: '',
    address: 'East Village, Plot 8',
    phone: '+62 813-2345-6789',
    experience: 15,
    landSize: 4.2,
    tobaccoVariety: 'Burley',
    certifications: ['GAP Certified'],
  },
  {
    id: '3',
    name: 'David Wong',
    age: 52,
    photo: '',
    address: 'South Village, Plot 5',
    phone: '+62 814-3456-7891',
    experience: 25,
    landSize: 7.8,
    tobaccoVariety: 'Oriental',
    certifications: ['Organic Certified', 'Fair Trade', 'GAP Certified'],
  },
  {
    id: '4',
    name: 'Sarah Johnson',
    age: 41,
    photo: '',
    address: 'West Village, Plot 15',
    phone: '+62 815-4567-8901',
    experience: 18,
    landSize: 6.3,
    tobaccoVariety: 'Virginia',
    certifications: ['GAP Certified'],
  },
  {
    id: '5',
    name: 'Ahmad Hassan',
    age: 48,
    photo: '',
    address: 'Central Village, Plot 3',
    phone: '+62 816-5678-9012',
    experience: 22,
    landSize: 5.0,
    tobaccoVariety: 'Burley',
    certifications: ['Organic Certified'],
  },
  {
    id: '6',
    name: 'Linda Chen',
    age: 36,
    photo: '',
    address: 'North Village, Plot 20',
    phone: '+62 817-6789-0123',
    experience: 12,
    landSize: 3.5,
    tobaccoVariety: 'Virginia',
    certifications: [],
  },
  {
    id: '7',
    name: 'Robert Miller',
    age: 55,
    photo: '',
    address: 'East Village, Plot 18',
    phone: '+62 818-7890-1234',
    experience: 30,
    landSize: 8.5,
    tobaccoVariety: 'Oriental',
    certifications: ['Organic Certified', 'GAP Certified'],
  },
  {
    id: '8',
    name: 'Priya Sharma',
    age: 42,
    photo: '',
    address: 'South Village, Plot 11',
    phone: '+62 819-8901-2345',
    experience: 16,
    landSize: 4.8,
    tobaccoVariety: 'Burley',
    certifications: ['Fair Trade'],
  },
];

export const mockPlantations: Plantation[] = [
  {
    id: 'p1',
    farmerId: '1',
    location: 'North Field A',
    size: 2.5,
    tobaccoVariety: 'Virginia',
    plantingDate: '2024-03-15',
    expectedHarvestDate: '2024-09-15',
    status: 'growing',
    soilType: 'Sandy Loam',
    irrigationType: 'Drip Irrigation',
  },
  {
    id: 'p2',
    farmerId: '1',
    location: 'North Field B',
    size: 3.0,
    tobaccoVariety: 'Virginia',
    plantingDate: '2024-04-01',
    expectedHarvestDate: '2024-10-01',
    status: 'growing',
    soilType: 'Clay Loam',
    irrigationType: 'Sprinkler',
  },
  {
    id: 'p3',
    farmerId: '2',
    location: 'East Field C',
    size: 4.2,
    tobaccoVariety: 'Burley',
    plantingDate: '2024-02-20',
    expectedHarvestDate: '2024-08-20',
    status: 'harvesting',
    soilType: 'Silt Loam',
    irrigationType: 'Flood Irrigation',
  },
  {
    id: 'p4',
    farmerId: '3',
    location: 'South Field D',
    size: 3.5,
    tobaccoVariety: 'Oriental',
    plantingDate: '2024-03-10',
    expectedHarvestDate: '2024-09-10',
    status: 'growing',
    soilType: 'Sandy Loam',
    irrigationType: 'Drip Irrigation',
  },
  {
    id: 'p5',
    farmerId: '3',
    location: 'South Field E',
    size: 4.3,
    tobaccoVariety: 'Oriental',
    plantingDate: '2024-01-15',
    expectedHarvestDate: '2024-07-15',
    status: 'harvested',
    soilType: 'Clay',
    irrigationType: 'Drip Irrigation',
  },
  {
    id: 'p6',
    farmerId: '4',
    location: 'West Field F',
    size: 6.3,
    tobaccoVariety: 'Virginia',
    plantingDate: '2024-05-01',
    expectedHarvestDate: '2024-11-01',
    status: 'planting',
    soilType: 'Loam',
    irrigationType: 'Sprinkler',
  },
  {
    id: 'p7',
    farmerId: '5',
    location: 'Central Field G',
    size: 5.0,
    tobaccoVariety: 'Burley',
    plantingDate: '2024-03-25',
    expectedHarvestDate: '2024-09-25',
    status: 'growing',
    soilType: 'Sandy Clay',
    irrigationType: 'Flood Irrigation',
  },
  {
    id: 'p8',
    farmerId: '6',
    location: 'North Field H',
    size: 3.5,
    tobaccoVariety: 'Virginia',
    plantingDate: '2024-04-10',
    expectedHarvestDate: '2024-10-10',
    status: 'growing',
    soilType: 'Silt Loam',
    irrigationType: 'Drip Irrigation',
  },
  {
    id: 'p9',
    farmerId: '7',
    location: 'East Field I',
    size: 4.0,
    tobaccoVariety: 'Oriental',
    plantingDate: '2024-02-10',
    expectedHarvestDate: '2024-08-10',
    status: 'harvesting',
    soilType: 'Sandy Loam',
    irrigationType: 'Sprinkler',
  },
  {
    id: 'p10',
    farmerId: '7',
    location: 'East Field J',
    size: 4.5,
    tobaccoVariety: 'Oriental',
    plantingDate: '2024-03-05',
    expectedHarvestDate: '2024-09-05',
    status: 'growing',
    soilType: 'Clay Loam',
    irrigationType: 'Drip Irrigation',
  },
  {
    id: 'p11',
    farmerId: '8',
    location: 'South Field K',
    size: 4.8,
    tobaccoVariety: 'Burley',
    plantingDate: '2024-01-20',
    expectedHarvestDate: '2024-07-20',
    status: 'harvested',
    soilType: 'Loam',
    irrigationType: 'Flood Irrigation',
  },
];
